services:
  db:
    container_name: symfony-t-price-checker-api-db
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tPriceChecker}
      POSTGRES_USER: ${POSTGRES_USER:-tPriceChecker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tPriceChecker}
    volumes:
      - ./pgdata:/var/lib/postgresql:rw
    ports:
      - "5432:5432"

  php:
    container_name: symfony-t-price-checker-api-php
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/var/www/html
    environment:
      XDEBUG_CONFIG: 'idekey=PHPSTORM remote_host=host.docker.internal remote_port=9000 remote_autostart=1 remote_enable=1 remote_mode=req remote_connect_back=0'
      PHP_IDE_CONFIG: 'serverName=tPriceChecker'
    expose:
      - 9000

  nginx:
    container_name: symfony-t-price-checker-api-nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
      - "443:443"


volumes:
  pgdata:
