services:
  db:
    container_name: symfony-t-price-checker-api-db
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tPriceChecker}
      POSTGRES_USER: ${POSTGRES_USER:-tPriceChecker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tPriceChecker}
    volumes:
      - ./pgdata:/var/lib/postgresql:rw
    ports:
      - "5432:5432"
    networks:
      - t-price-checker-api

  php:
    container_name: symfony-t-price-checker-api-php
    build:
      context: ./docker/php-fpm
    volumes:
      - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./app:/var/www/html
      # Фикс для windows (ускорение работы symfony)
      - /var/www/html/vendor
    networks:
      - t-price-checker-api

  nginx:
    container_name: symfony-t-price-checker-api-nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - db
    networks:
      - t-price-checker-api


volumes:
  pgdata:

networks:
  t-price-checker-api: