# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $collectionProvider: '@api_platform.doctrine.orm.state.collection_provider'
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'

    App\:
        resource: '../src/'

    # Фильтрация по userCreated в зависимых моделях
    App\Doctrine\ORM\Extension\UserCreatedFilterExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: -60 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    # Фильтрация по типу магазина
    App\Doctrine\ORM\Extension\ShopFilterExtension:
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 10 }
            - { name: api_platform.doctrine.orm.query_extension.item }

    # Проверка значений пришедших в headers
    App\EventListener\HeaderCheckListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest' }
