<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260714085513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '<<<EOF
        1) Удаление поля id из таблицы product_price
        2) Добавление поля date_created_string в таблицу product_price
        3) Добавление уникального индекса из полей product_id, user_created_id, date_created_string в таблицу product_price
        4) Удаление поля id из таблицы product_stock
        5) Добавление поля date_created_string в таблицу product_stock
        6) Добавление уникального индекса из полей product_id, user_created_id, date_created_string в таблицу product_stock
        EOF ';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT product_price_pkey');
        $this->addSql('ALTER TABLE product_price DROP id');
        $this->addSql('ALTER TABLE product_price ADD date_created_string VARCHAR(25) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX pp_product_user_date ON product_price (product_id, user_created_id, date_created_string)');
        $this->addSql('ALTER TABLE product_price ADD PRIMARY KEY (product_id, user_created_id, date_created_string)');

        $this->addSql('ALTER TABLE product_stock DROP CONSTRAINT product_stock_pkey');
        $this->addSql('ALTER TABLE product_stock ADD date_created_string VARCHAR(25) NOT NULL');
        $this->addSql('ALTER TABLE product_stock DROP id');
        $this->addSql('CREATE UNIQUE INDEX ps_product_user_date ON product_stock (product_id, user_created_id, date_created_string)');
        $this->addSql('ALTER TABLE product_stock ADD PRIMARY KEY (product_id, user_created_id, date_created_string)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT product_price_pkey');
        $this->addSql('DROP INDEX pp_product_user_date');
        $this->addSql('ALTER TABLE product_price DROP date_created_string');
        $this->addSql('ALTER TABLE product_price ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE product_price ADD PRIMARY KEY (id)');

        $this->addSql('ALTER TABLE product_stock DROP CONSTRAINT product_stock_pkey');
        $this->addSql('DROP INDEX ps_product_user_date');
        $this->addSql('ALTER TABLE product_stock ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE product_stock DROP date_created_string');
        $this->addSql('ALTER TABLE product_stock ADD PRIMARY KEY (id)');
    }
}
