<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260709103427 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '<<<EOF
        1) Добавление таблицы access_token (генерируемые токены авторизации)
        2) Добавление таблицы book (Книги)
        3) Добавление таблицы book_author (Автор книги)
        4) Добавление таблицы book_binding_type (Тип переплёта)
        5) Добавление таблицы book_publishing_brand (Издательский брэнд)
        6) Добавление таблицы book_publishing_house (Издательский дом)
        7) Добавление таблицы book_series (Серия)
        EOF ';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE access_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, user_identifier VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B6A2DD685F37A13B ON access_token (token)');
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, original_title VARCHAR(255) DEFAULT NULL, isbn VARCHAR(30) DEFAULT NULL, pages SMALLINT DEFAULT NULL, circulation INT DEFAULT NULL, size VARCHAR(20) NOT NULL, publish_year SMALLINT NOT NULL, livelib_id INT DEFAULT NULL, goodreads_id INT DEFAULT NULL, fantlab_id VARCHAR(100) DEFAULT NULL, livelib_rating DOUBLE PRECISION DEFAULT NULL, goodreads_rating DOUBLE PRECISION DEFAULT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, book_author_id INT NOT NULL, binding_type_id INT NOT NULL, publishing_house_id INT DEFAULT NULL, publishing_brand_id INT DEFAULT NULL, book_series_id INT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBE5A331E4DBE55D ON book (book_author_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A331C832C4F1 ON book (binding_type_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A33167402924 ON book (publishing_house_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A3314802BC39 ON book (publishing_brand_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A33140D627DA ON book (book_series_id)');
        $this->addSql('CREATE INDEX IDX_CBE5A331A76ED395 ON book (user_id)');
        $this->addSql('COMMENT ON TABLE book IS \'Книги\'');
        $this->addSql('CREATE TABLE book_author (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE book_author IS \'Автор книги\'');
        $this->addSql('CREATE TABLE book_binding_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE book_binding_type IS \'Тип переплёта\'');
        $this->addSql('CREATE TABLE book_publishing_brand (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE book_publishing_brand IS \'Издательский брэнд\'');
        $this->addSql('CREATE TABLE book_publishing_house (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE book_publishing_house IS \'Издательский дом\'');
        $this->addSql('CREATE TABLE book_series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE book_series IS \'Серия\'');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A331E4DBE55D FOREIGN KEY (book_author_id) REFERENCES book_author (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A331C832C4F1 FOREIGN KEY (binding_type_id) REFERENCES book_binding_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A33167402924 FOREIGN KEY (publishing_house_id) REFERENCES book_publishing_house (id)');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A3314802BC39 FOREIGN KEY (publishing_brand_id) REFERENCES book_publishing_brand (id)');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A33140D627DA FOREIGN KEY (book_series_id) REFERENCES book_series (id)');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A331A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A331E4DBE55D');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A331C832C4F1');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A33167402924');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A3314802BC39');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A33140D627DA');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A331A76ED395');
        $this->addSql('DROP TABLE access_token');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE book_author');
        $this->addSql('DROP TABLE book_binding_type');
        $this->addSql('DROP TABLE book_publishing_brand');
        $this->addSql('DROP TABLE book_publishing_house');
        $this->addSql('DROP TABLE book_series');
    }
}
