<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260710064523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '<<<EOF
        1) Добавление таблицы city (город)
        2) Добавление таблицы product (продукт)
        3) Добавление таблицы product_price (цена продукта)
        4) Добавление таблицы product_stock (сток продукта)
        5) Добавление таблицы shop (магазин)
        6) Добавление таблицы source_product (источник товара)
        7) Добавление таблицы source_product_type (тип источника товара)
        EOF ';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(4) NOT NULL, title VARCHAR(255) NOT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE city IS \'Город\'');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, shop_product_id VARCHAR(30) NOT NULL, shop_product_code VARCHAR(20) DEFAULT NULL, title VARCHAR(255) NOT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_product_id INT DEFAULT NULL, book_id INT DEFAULT NULL, shop_id INT NOT NULL, city_id INT DEFAULT NULL, user_created_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD3930177E ON product (source_product_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD16A2B381 ON product (book_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD4D16C4DD ON product (shop_id)');
        $this->addSql('CREATE INDEX IDX_D34A04AD8BAC62AF ON product (city_id)');
        $this->addSql('CREATE INDEX IDX_D34A04ADF987D8A8 ON product (user_created_id)');
        $this->addSql('COMMENT ON TABLE product IS \'Продукт\'');
        $this->addSql('CREATE TABLE product_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, product_id INT NOT NULL, user_created_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B9459854584665A ON product_price (product_id)');
        $this->addSql('CREATE INDEX IDX_6B945985F987D8A8 ON product_price (user_created_id)');
        $this->addSql('COMMENT ON TABLE product_price IS \'Цена продукта\'');
        $this->addSql('CREATE TABLE product_stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, qty INT NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, log JSON DEFAULT NULL, product_id INT NOT NULL, user_created_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA6A2D3C4584665A ON product_stock (product_id)');
        $this->addSql('CREATE INDEX IDX_EA6A2D3CF987D8A8 ON product_stock (user_created_id)');
        $this->addSql('COMMENT ON TABLE product_stock IS \'Сток продукта\'');
        $this->addSql('CREATE TABLE shop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, domain VARCHAR(50) NOT NULL, url TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE shop IS \'Магазин\'');
        $this->addSql('CREATE TABLE source_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_product_type_id INT NOT NULL, user_created_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9A95BCC5B28AB928 ON source_product (source_product_type_id)');
        $this->addSql('CREATE INDEX IDX_9A95BCC5F987D8A8 ON source_product (user_created_id)');
        $this->addSql('COMMENT ON TABLE source_product IS \'Источник товара\'');
        $this->addSql('CREATE TABLE source_product_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(50) NOT NULL, date_updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE source_product_type IS \'Тип источника товара\'');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD3930177E FOREIGN KEY (source_product_id) REFERENCES source_product (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD16A2B381 FOREIGN KEY (book_id) REFERENCES book (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD4D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADF987D8A8 FOREIGN KEY (user_created_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B9459854584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B945985F987D8A8 FOREIGN KEY (user_created_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_stock ADD CONSTRAINT FK_EA6A2D3C4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_stock ADD CONSTRAINT FK_EA6A2D3CF987D8A8 FOREIGN KEY (user_created_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE source_product ADD CONSTRAINT FK_9A95BCC5B28AB928 FOREIGN KEY (source_product_type_id) REFERENCES source_product_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE source_product ADD CONSTRAINT FK_9A95BCC5F987D8A8 FOREIGN KEY (user_created_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT fk_cbe5a331a76ed395');
        $this->addSql('DROP INDEX idx_cbe5a331a76ed395');
        $this->addSql('ALTER TABLE book RENAME COLUMN user_id TO user_created_id');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A331F987D8A8 FOREIGN KEY (user_created_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_CBE5A331F987D8A8 ON book (user_created_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD3930177E');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD16A2B381');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD4D16C4DD');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD8BAC62AF');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04ADF987D8A8');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B9459854584665A');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B945985F987D8A8');
        $this->addSql('ALTER TABLE product_stock DROP CONSTRAINT FK_EA6A2D3C4584665A');
        $this->addSql('ALTER TABLE product_stock DROP CONSTRAINT FK_EA6A2D3CF987D8A8');
        $this->addSql('ALTER TABLE source_product DROP CONSTRAINT FK_9A95BCC5B28AB928');
        $this->addSql('ALTER TABLE source_product DROP CONSTRAINT FK_9A95BCC5F987D8A8');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_price');
        $this->addSql('DROP TABLE product_stock');
        $this->addSql('DROP TABLE shop');
        $this->addSql('DROP TABLE source_product');
        $this->addSql('DROP TABLE source_product_type');
        $this->addSql('ALTER TABLE book DROP CONSTRAINT FK_CBE5A331F987D8A8');
        $this->addSql('DROP INDEX IDX_CBE5A331F987D8A8');
        $this->addSql('ALTER TABLE book RENAME COLUMN user_created_id TO user_id');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT fk_cbe5a331a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_cbe5a331a76ed395 ON book (user_id)');
    }
}
